name: Test Go Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.name || matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: ubuntu-22.04
          - os: macos-latest
          - os: macos-13
          - os: windows-latest
          - os: ubuntu-latest
            name: alpine-latest
            container: alpine:latest
          - os: ubuntu-latest
            name: almalinux-9
            container: almalinux:9
          - os: ubuntu-latest
            name: almalinux-8
            container: almalinux:8
          - os: ubuntu-latest
            name: opensuse-leap
            container: opensuse/leap:latest
          - os: ubuntu-latest
            name: opensuse-tumbleweed
            container: opensuse/tumbleweed:latest
          - os: ubuntu-latest
            name: archlinux
            container: archlinux:latest
          - os: ubuntu-latest
            name: gentoo
            container: gentoo/stage3:latest
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    
    steps:
    - name: Install essential tools for checkout (openSUSE)
      if: startsWith(matrix.container || '', 'opensuse')
      run: |
        zypper --non-interactive install tar gzip
    
    - name: Install essential tools for checkout (Arch Linux)
      if: matrix.container == 'archlinux:latest'
      run: |
        pacman -Sy --noconfirm tar gzip
    
    - name: Install essential tools for checkout (Gentoo)
      if: matrix.container == 'gentoo/stage3:latest'
      run: |
        # Gentoo stage3 should have tar and gzip already
        # Just verify they exist
        which tar gzip || emerge -q app-arch/tar app-arch/gzip
    
    - uses: actions/checkout@v4
    
    - name: Install Alpine dependencies
      if: matrix.container == 'alpine:latest'
      run: |
        apk add --no-cache bash go git curl wget
        mkdir -p $HOME/go/bin
        echo "export PATH=$HOME/go/bin:$PATH" >> $HOME/.profile
    
    - name: Install AlmaLinux dependencies
      if: startsWith(matrix.container || '', 'almalinux')
      run: |
        dnf install -y epel-release
        # Use --allowerasing to replace curl-minimal with full curl
        dnf install -y --allowerasing bash git curl wget tar gzip which
        # Install Go from EPEL or download it
        dnf install -y golang || {
          # If Go is not in repos, download and install it
          curl -L https://go.dev/dl/go1.21.13.linux-amd64.tar.gz -o /tmp/go.tar.gz
          tar -C /usr/local -xzf /tmp/go.tar.gz
          echo 'export PATH=/usr/local/go/bin:$PATH' >> /etc/profile
          export PATH=/usr/local/go/bin:$PATH
        }
        mkdir -p $HOME/go/bin
        echo "export PATH=$HOME/go/bin:$PATH" >> $HOME/.bash_profile
    
    - name: Install openSUSE dependencies
      if: startsWith(matrix.container || '', 'opensuse')
      run: |
        # Update package index
        zypper --non-interactive refresh
        # Install required packages (tar and gzip already installed for checkout)
        # Note: wget seems to have issues on Tumbleweed, ensure curl is available
        zypper --non-interactive install bash git curl which findutils
        # Install Go
        zypper --non-interactive install go || {
          # If Go is not in repos, download and install it
          curl -L https://go.dev/dl/go1.21.13.linux-amd64.tar.gz -o /tmp/go.tar.gz
          tar -C /usr/local -xzf /tmp/go.tar.gz
          # Clean up PATH (remove empty entries) and set it properly
          export PATH="/usr/local/go/bin:${PATH//::/:}"
          export PATH="${PATH#:}"
          export PATH="${PATH%:}"
          echo 'export PATH="/usr/local/go/bin:$PATH"' >> /etc/profile
        }
        mkdir -p $HOME/go/bin
        echo 'export PATH="$HOME/go/bin:$PATH"' >> $HOME/.bash_profile
    
    - name: Install Arch Linux dependencies
      if: matrix.container == 'archlinux:latest'
      run: |
        # Update package database and upgrade system
        pacman -Syu --noconfirm
        # Install required packages
        pacman -S --noconfirm bash git curl wget which findutils go
        mkdir -p $HOME/go/bin
        echo "export PATH=$HOME/go/bin:$PATH" >> $HOME/.bash_profile
    
    - name: Install Gentoo dependencies
      if: matrix.container == 'gentoo/stage3:latest'
      run: |
        # Initialize Portage repository
        emerge-webrsync
        # Install required packages
        emerge -q app-shells/bash dev-vcs/git net-misc/curl net-misc/wget sys-apps/which sys-apps/findutils
        # Install Go - download directly since emerge would take too long to compile
        curl -L https://go.dev/dl/go1.21.13.linux-amd64.tar.gz -o /tmp/go.tar.gz
        tar -C /usr/local -xzf /tmp/go.tar.gz
        # Clean up PATH (remove empty entries) and set it properly
        export PATH="/usr/local/go/bin:${PATH//::/:}"
        export PATH="${PATH#:}"
        export PATH="${PATH%:}"
        echo "export PATH=\"/usr/local/go/bin:\$PATH\"" >> /etc/profile
        mkdir -p $HOME/go/bin
        echo "export PATH=\"\$HOME/go/bin:\$PATH\"" >> $HOME/.bash_profile
    
    - name: Set up Go
      if: matrix.container == null
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Make scripts executable
      run: chmod +x gman test-go-scripts.sh test-path-setup.sh test-list-available.sh test-alpine-detection.sh test-distro-detection.sh
      if: runner.os != 'Windows'
    
    - name: Run PATH setup tests (Unix)
      run: ./test-path-setup.sh
      if: runner.os != 'Windows'
    
    - name: Run installation tests (Unix)
      run: ./test-go-scripts.sh
      if: runner.os != 'Windows'
    
    - name: Run list-available tests (Unix)
      run: ./test-list-available.sh
      if: runner.os != 'Windows'
    
    - name: Run distribution detection tests (Unix)
      run: ./test-distro-detection.sh
      if: runner.os != 'Windows'
    
    - name: Run Alpine detection tests (Unix)
      run: ./test-alpine-detection.sh
      if: runner.os != 'Windows'
    
    - name: Run PATH setup tests (Windows)
      run: ./test-path-setup.sh
      shell: bash
      if: runner.os == 'Windows'
    
    - name: Run installation tests (Windows)
      run: ./test-go-scripts.sh
      shell: bash
      if: runner.os == 'Windows'
    
    - name: Run list-available tests (Windows)
      run: ./test-list-available.sh
      shell: bash
      if: runner.os == 'Windows'
    
    - name: Run distribution detection tests (Windows)
      run: ./test-distro-detection.sh
      shell: bash
      if: runner.os == 'Windows'
    
    - name: Run Alpine detection tests (Windows)
      run: ./test-alpine-detection.sh
      shell: bash
      if: runner.os == 'Windows'