name: Test Go Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, macos-latest, macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Make scripts executable
      run: chmod +x gman test-go-scripts.sh test-path-setup.sh
      if: runner.os != 'Windows'
    
    - name: Run PATH setup tests (Unix)
      run: ./test-path-setup.sh
      if: runner.os != 'Windows'
    
    - name: Run installation tests (Unix)
      run: ./test-go-scripts.sh
      if: runner.os != 'Windows'
    
    - name: Run PATH setup tests (Windows)
      run: bash ./test-path-setup.sh
      if: runner.os == 'Windows'
    
    - name: Run installation tests (Windows)
      run: bash ./test-go-scripts.sh
      if: runner.os == 'Windows'