name: Test Go Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Make test scripts executable
      run: chmod +x test-go-scripts.sh test-path-setup.sh
    
    - name: Run PATH setup tests
      run: ./test-path-setup.sh
    
    - name: Run installation tests
      run: ./test-go-scripts.sh