name: Test Go Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, macos-latest, macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Make scripts executable
      run: chmod +x gman test-go-scripts.sh test-path-setup.sh test-list-available.sh
      if: runner.os != 'Windows'
    
    - name: Run PATH setup tests (Unix)
      run: ./test-path-setup.sh
      if: runner.os != 'Windows'
    
    - name: Run installation tests (Unix)
      run: ./test-go-scripts.sh
      if: runner.os != 'Windows'
    
    - name: Run list-available tests (Unix)
      run: ./test-list-available.sh
      if: runner.os != 'Windows'
    
    - name: Run PATH setup tests (Windows)
      run: ./test-path-setup.sh
      shell: bash
      if: runner.os == 'Windows'
    
    - name: Run installation tests (Windows)
      run: ./test-go-scripts.sh
      shell: bash
      if: runner.os == 'Windows'
    
    - name: Run list-available tests (Windows)
      run: ./test-list-available.sh
      shell: bash
      if: runner.os == 'Windows'

  test-alpine:
    name: Test on Alpine Linux
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        apk add --no-cache bash go git curl wget
    
    - name: Set up Go environment
      run: |
        mkdir -p $HOME/go/bin
        echo "export PATH=$HOME/go/bin:$PATH" >> $HOME/.profile
        source $HOME/.profile
    
    - name: Make scripts executable
      run: chmod +x gman test-go-scripts.sh test-path-setup.sh test-list-available.sh
    
    - name: Run PATH setup tests
      run: ./test-path-setup.sh
    
    - name: Run installation tests
      run: ./test-go-scripts.sh
    
    - name: Run list-available tests
      run: ./test-list-available.sh